on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-init
        with:
          args: 'init "-l config"'
      - name: West Update
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-update
        with:
          args: 'update'
      - name: West Config Zephyr Base
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-config
        with:
          args: 'config "--global zephyr.base-prefer configfile"'
      - name: West Zephyr Export
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-zephyr-export
        with:
          args: 'zephyr-export'


      - name: West Build (SP56 Left)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-sp56-left
        with:
          args: 'build "-s zmk/app -b sp56_left -d sp56_left -- -DZMK_CONFIG=/github/workspace/config"'
      - name: SP56 DTS File
        if: ${{ always() }}
        run: cat sp56_left/zephyr/sp56_left.dts.pre.tmp
      - name: SP56 Left Kconfig file
        run: cat sp56_left/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp sp56_left/zephyr/zmk.uf2 sp56_left.uf2
      - name: Archive (SP56 Left)
        uses: actions/upload-artifact@v2
        with:
          name: sp56_left
          path: sp56_left.uf2


      - name: West Build (SP56 Right)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-sp56-right
        with:
          args: 'build "-s zmk/app -b sp56_right -d sp56_right -- -DZMK_CONFIG=/github/workspace/config"'
      - name: SP56 DTS File
        if: ${{ always() }}
        run: cat sp56_right/zephyr/sp56_right.dts.pre.tmp
      - name: SP56 Right Kconfig file
        run: cat sp56_right/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp sp56_right/zephyr/zmk.uf2 sp56_right.uf2
      - name: Archive (SP56 Right)
        uses: actions/upload-artifact@v2
        with:
          name: sp56_right
          path: sp56_right.uf2


      - name: West Build (SF65)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-sf65
        with:
          args: 'build "-s zmk/app -b sf65 -d sf65 -- -DZMK_CONFIG=/github/workspace/config"'
      - name: SF65 DTS File
        if: ${{ always() }}
        run: cat sf65/zephyr/sf65.dts.pre.tmp
      - name: SF65 Kconfig file
        run: cat sf65/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp sf65/zephyr/zmk.uf2 sf65.uf2
      - name: Archive (SF65)
        uses: actions/upload-artifact@v2
        with:
          name: sf65
          path: sf65.uf2
        
      - name: West Build (Z18)
        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
        id: west-build-z18
        with:
          args: 'build "-s zmk/app -b z18 -d z18 -- -DZMK_CONFIG=/github/workspace/config"'
      - name: Z18 DTS File
        if: ${{ always() }}
        run: cat z18/zephyr/z18.dts.pre.tmp
      - name: Z18 Kconfig file
        run: cat z18/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp z18/zephyr/zmk.uf2 z18.uf2
      - name: Archive (Z18)
        uses: actions/upload-artifact@v2
        with:
          name: z18
          path: z18.uf2